<#
replace <yourgmailaccount> with your own Gmail account name, omit @gmail.com
replace <App password generated by Gmail see Figure 15.55> accordingly with the password generated as instructed, see Figure 15.55
#>
$SMTPServer = "smtp.gmail.com"
$SMTPClient = New-Object Net.Mail.SmtpClient($SmtpServer, 587)
$SMTPClient.EnableSsl = $true
$SMTPClient.Credentials = New-Object System.Net.NetworkCredential("<yourgmailaccount>", "<App password generated by Gmail see Figure 15.55>");
$SMTPClient.Send($EmailFrom, $EmailTo, $Subject, $Body)